buildscript {
    ext {
        agp_version = '8.10.1'
        junit_version = '4.13.2'
        slf4j_version = '2.0.7'
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
    }
}

allprojects {
    version = "1.4"
    group = 'org.mp4parser'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17

        withSourcesJar()
        withJavadocJar()
    }

    publishing {
        publications {
            maven(MavenPublication) {
                groupId project.group
                artifactId project.name
                version project.version
                from components.java
            }
        }
    }

    tasks.withType(Test).configureEach { enabled = false }
    tasks.withType(Javadoc).configureEach { enabled = false }
}
