dependencies {
    implementation 'org.aspectj:aspectjrt:1.9.19'
    implementation "org.slf4j:slf4j-api:$slf4j_version"

    testImplementation 'commons-codec:commons-codec:1.18.0'
    testImplementation 'commons-io:commons-io:2.16.1'
    testImplementation "junit:junit:$junit_version"
    testImplementation "org.slf4j:slf4j-simple:$slf4j_version"
}
